export { PortfolioSlider } from './slider'
// export {HeroSlider} from './slider'
export {ProjectGrid} from './slider'
export {default as AnimatedText} from './animate/text/AnimatedText'
export {default as ScrollToTop} from './scroll-to-top/ScrollToTop'
export {default as LanguageSwitcher} from './language-switcher/LanguageSwitcher '
