version: '3.9'
services:
  next-app:
    build: .
    container_name: next-app
    ports:
      - "3034:3000"
    volumes:
      # Монтируем папку с базой данных на хосте в контейнер
      - ./db:/app/db
      # Монтируем папку для загрузки файлов
      - ./public/uploads:/app/public/uploads
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - DB_PATH=/app/db/gallery.db
    restart: always
