export const keywords = [
    'Developer',
    'Frontend Developer',
    'Fullstack Developer',
    'Backend Developer',
    'Software Engineer',
    'React',
    'Next.js',
    'Nest.js',
    'TypeScript',
    'JavaScript',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Framer Motion',
    'Firebase',
    'Redis',
    'BullMQ',
    'Websockets',
    'Feature-Slice Design',
    'Onion Architecture',
    'FSD',
    'Figma',
    'Photoshop',
    'Illustrator',
    'Premiere Pro',
    'After Effects',
    'Python',
    'FastAPI',
    'REST API',
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'RabbitMQ',
    'Docker',
];
