// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import LoadingScreen from "@/modules/shared/LoadingScreen/ui/LoadingScreen";
import "@/styles/globals.css";
// import { Providers } from "@/modules/app";
import { Footer, Header } from "@/modules/widgetes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Admin",
//   description: "Generated by create next app",
// };

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <div className="relative">
      <LoadingScreen />

      <div className="fixed w-full z-10">
        <Header />
      </div>

      {children}


      <Footer />

    </div>
  );
}

